# Generated by Django 2.2.5 on 2019-10-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogStop', '0002_auto_20191015_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Science', max_length=20, verbose_name='Categories'),
        ),
    ]
