# Generated by Django 2.2.5 on 2019-10-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogStop', '0005_auto_20191015_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manage_Blog_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_background_image', models.ImageField(upload_to='home_background_image')),
                ('detail_background_image', models.ImageField(upload_to='detail_background_image')),
                ('book_background_image', models.ImageField(upload_to='book_background_image')),
                ('book1_image', models.ImageField(upload_to='suggested_books')),
                ('book2_image', models.ImageField(upload_to='suggested_books')),
                ('book3_image', models.ImageField(upload_to='suggested_books')),
                ('book4_image', models.ImageField(upload_to='suggested_books')),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='content_1',
        ),
        migrations.AddField(
            model_name='post',
            name='content_2',
            field=models.TextField(default='lorem lorem lorem '),
        ),
    ]
