# Generated by Django 2.2.5 on 2019-10-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogStop', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_published_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
