# Generated by Django 2.2.5 on 2019-10-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogStop', '0008_post_post_published_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_published_time',
            field=models.TimeField(default=None),
        ),
    ]
