# Generated by Django 2.2.5 on 2019-10-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogStop', '0011_auto_20191031_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_published_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_published_date',
            field=models.DateTimeField(),
        ),
    ]
