# Generated by Django 2.2.5 on 2019-10-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogStop', '0012_auto_20191031_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image_caption',
            field=models.CharField(default='Every thing we do', max_length=250),
        ),
    ]
