# Generated by Django 2.2.5 on 2019-11-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogStop', '0017_auto_20191102_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image_url',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
