# Generated by Django 2.2.5 on 2019-11-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogStop', '0018_auto_20191102_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='about',
            field=models.TextField(default='Hello world'),
        ),
    ]
