# Generated by Django 2.2.5 on 2019-11-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogStop', '0019_category_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(default='Hello world')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='about',
        ),
    ]
